# -*- coding: utf-8 -*-
"""Load a file and split into chunks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDSYU7c7332H47Lv0OsZbsNyBPv-rV1s
"""

!pip install langchain-community pypdf

from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]

from langchain_community.document_loaders import TextLoader, PyPDFLoader

if file_path.lower().endswith(".txt"):
    loader = TextLoader(file_path)
else:
    loader = PyPDFLoader(file_path)

docs = loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=50)
chunks = splitter.split_documents(docs)

print(f"Total chunks created: {len(chunks)}")