# -*- coding: utf-8 -*-
"""transformers&Hugging Face Transformers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRNHAgWFKqSNcoNxOLsFJzzAupRQeoJO
"""

!pip install transformers

from transformers import pipeline

generator = pipeline("text2text-generation", model="google/flan-t5-base")

prompt1 = "Explain how rainbows are formed"
response1 = generator(prompt1, max_length=200)

print("Task 1 - Prompt:", prompt1)
print("Task 1 - Response:", response1[0]['generated_text'])
print("\n" + "="*80 + "\n")

prompt2 = "Write a small poem about the ocean"
response2 = generator(prompt2, max_length=50)

print("Task 2 - Prompt:", prompt2)
print("Task 2 - Response:", response2[0]['generated_text'])